//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlaTerceiros.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa_Empresa
    {
        public int pessoa_empresa_id { get; set; }
        public int responsavel_id { get; set; }
        public int empresa_id { get; set; }
        public int pessoa_id { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_termino { get; set; }
        public string registro_iamspe { get; set; }
        public string numero_proximidade_cracha { get; set; }
        public string descricao_funcao { get; set; }
        public System.DateTime registro_criado_em { get; set; }
        public System.DateTime registro_alterado_em { get; set; }
        public string registro_alterado_por { get; set; }
        public byte[] registro_versao { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Responsavel Responsavel { get; set; }
    }
}
