//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlaTerceiros.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsavel
    {
        public Responsavel()
        {
            this.Pessoa_Empresa = new HashSet<Pessoa_Empresa>();
        }
    
        public int responsavel_id { get; set; }
        public string registro_iamspe { get; set; }
        public string nome_completo { get; set; }
        public string ramal { get; set; }
        public System.DateTime registro_criado_em { get; set; }
        public System.DateTime registro_alterado_em { get; set; }
        public string registro_alterado_por { get; set; }
        public byte[] registro_versao { get; set; }
    
        public virtual ICollection<Pessoa_Empresa> Pessoa_Empresa { get; set; }
    }
}
